[package]
name = "dualshock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dual-shock4-controller = "0.1.1"
moving_avg = "0.2.0"
